name: "workflow_runner"
description: ""

inputs:
  token:
    description: ""
    required: true
  workflow_name:
    description: ""
    required: true
  branch:
    description: ""
    required: false
    default: "main"


runs:
  using: "composite"
  steps:

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install requests
        shell: bash
        run: pip install requests==2.31.0

      - name: run workflow ${{inputs.workflow_name}}
        shell: bash
        run: |
          echo "${{github.action_path}}"
          ls -l ${{github.action_path}}
#          ./workflow_runner.py ${{inputs.token}} ${{inputs.workflow_name}} ${{inputs.branch}}