name: "setup-python"
description: ""

runs:
  using: composite

  steps:
    - name: add repository
      shell: bash
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt update -y && sudo apt upgrade -y

    - name: install python 3.11
      shell: bash
      run: sudo apt install python3.11

    - name: install pip
      shell: bash
      run: sudo apt install python3-pip