name: "ssh delivery"
description: ""


inputs:
  remote_user:
    required: true
    description: ""
  remote_host:
    required: true
    description: ""
  remote_port:
    required: false
    description: ""
    default: "22"
  ssh_private_key:
    required: true
    description: ""
  target:
    required: true
    description: ""

runs:
  using: composite

  steps:
    - name: set up ssh key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{inputs.ssh_private_key}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H -p ${{inputs.remote_port}} ${{inputs.remote_host}} >> ~/.ssh/known_hosts

    - name: deliver project to remote server
      shell: bash
      run: |
        sudo chown -R $USER:1000 $PWD
        sudo scp -o StrictHostKeyChecking=no \
        -P ${{inputs.remote_port}} \
        -r $PWD ${{inputs.remote_user}}@${{inputs.remote_host}}:${{inputs.target}}