name: "ssh delivery"
description: ""


inputs:
  command:
    required: true
    description: ""
  remote_user:
    required: true
    description: ""
  remote_host:
    required: true
    description: ""
  remote_port:
    required: false
    description: ""
    default: "22"
  ssh_private_key:
    required: true
    description: ""

runs:
  using: composite

  steps:

    - name: set up ssh key
      shell: bash
      run: |
        mkdir ~/.ssh
        echo "${{inputs.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H -p ${{inputs.REMOTE_PORT}} ${{inputs.REMOTE_HOST}} >> ~/.ssh/known_hosts

    - name: run command
      shell: bash
      run: |
        sudo ssh -p  ${{inputs.REMOTE_PORT}} ${{inputs.REMOTE_USER}}@${{inputs.REMOTE_HOST}} \
        '${{inputs.command}}'
